# Generated by Django 3.2.4 on 2022-07-04 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(blank=True, default='media/default.jpeg', upload_to='users/%Y/%m/%d')),
                ('level', models.CharField(blank=True, default='junior', max_length=200)),
                ('gender', models.CharField(choices=[('select', 'select'), ('male', 'male'), ('female', 'female')], default='select', max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('nationality', models.CharField(blank=True, default='Nigeria', max_length=100)),
                ('state', models.CharField(blank=True, default='Ogun', max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=100)),
                ('staff_id', models.CharField(blank=True, max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
