# Generated by Django 3.2.4 on 2022-07-04 06:48

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_type', models.CharField(choices=[('select account', 'select account'), ('HOD', 'HOD'), ('lecturer', 'lecturer'), ('Assessment committee', 'Assessment committee')], default='select account', max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(choices=[('select account', 'select account'), ('single', 'single'), ('married', 'married'), ('divorced', 'divorced')], default='select account', max_length=100)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('date_of_first_appointment', models.DateField(blank=True)),
                ('grade_of_first_appointment', models.CharField(blank=True, max_length=200)),
                ('date_of_last_promotion', models.DateField(blank=True)),
                ('grade_of_last_promotion', models.CharField(blank=True, max_length=200)),
                ('date_of_current_appointment', models.DateField(blank=True)),
                ('grade_of_current_appointment', models.CharField(blank=True, max_length=200)),
                ('appointment_confirmation', models.CharField(choices=[('select account', 'select account'), ('Yes', 'Yes'), ('No', 'No')], default='select account', max_length=100)),
                ('present_salary', models.CharField(blank=True, max_length=200)),
                ('academic_qualification_degree', models.CharField(blank=True, max_length=200)),
                ('academic_qualification_class', models.CharField(blank=True, max_length=200)),
                ('academic_qualification_institution', models.CharField(blank=True, max_length=200)),
                ('date_of_award', models.DateField()),
                ('professional_qualification', models.CharField(blank=True, max_length=200)),
                ('professional_awarding_body', models.CharField(blank=True, max_length=200)),
                ('professional_date_of_award', models.DateField()),
                ('teaching_experience_institution', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('courses_taught_during_harmattan', models.CharField(blank=True, max_length=600)),
                ('courses_taught_during_rain', models.CharField(blank=True, max_length=600)),
                ('professional_employer', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('nature_of_duty', models.CharField(blank=True, max_length=200)),
                ('professional_experience_date', models.DateField()),
                ('dissertation_of_thesis', models.FileField(upload_to='files/')),
                ('research_topic', models.CharField(blank=True, max_length=500)),
                ('research_date', models.CharField(blank=True, max_length=200)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HODAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_of_teaching', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('current_research', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('quality_of_research', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('quality_of_publications', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('postgraduate_supervision', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('other_departmental_responsibilities', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('contribution_to_university_or_country', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('general_assessment', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200)),
                ('recommendations', models.CharField(blank=True, choices=[('select', 'select'), ('Approved', 'Approved'), ('Unapproved', 'Unapproved')], default='select', max_length=200)),
                ('signature', models.CharField(blank=True, choices=[('select', 'select'), ('Signed & Approved', 'Signed & Approved'), ('Unsigned &Unapproved', 'Unsigned &Unapproved')], default='select', max_length=200)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('comment_by_member_of_staff', models.CharField(blank=True, max_length=200)),
                ('hod_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_fullname', to=settings.AUTH_USER_MODEL)),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecturer_form', to='appraisal_component.staffappraisal')),
            ],
        ),
        migrations.CreateModel(
            name='CPCAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_of_teaching', models.CharField(blank=True, choices=[('Select', 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='Select', max_length=200)),
                ('quality_of_research', models.CharField(blank=True, choices=[('Select', 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='Select', max_length=200)),
                ('quality_of_publication', models.CharField(blank=True, choices=[('Select', 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='Select', max_length=200)),
                ('contribution_to_university_or_country', models.CharField(blank=True, choices=[('Select', 'Select'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='Select', max_length=200)),
                ('academic_qualification_score', models.CharField(blank=True, default='ungraded', max_length=200)),
                ('teaching_score', models.CharField(blank=True, default='ungraded', max_length=200)),
                ('admistrative_experience_score', models.CharField(blank=True, default='ungraded', max_length=200)),
                ('current_research_score', models.CharField(blank=True, default='ungraded', max_length=200)),
                ('contribution_to_university_or_country_score', models.CharField(default='ungraded', max_length=200)),
                ('interview_experience_score', models.CharField(default='ungraded', max_length=200)),
                ('remarks', models.CharField(blank=True, default='no remarks yet!', max_length=200)),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('signature', models.CharField(blank=True, choices=[('select', 'select'), ('Signed & Approved', 'Signed & Approved'), ('Unsigned &Unapproved', 'Unsigned &Unapproved')], default='select', max_length=200)),
                ('cpc_member', models.ForeignKey(blank=True, default='cpc_staff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_of_staff', to=settings.AUTH_USER_MODEL)),
                ('which_lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='which_lecturer', to='appraisal_component.staffappraisal')),
            ],
        ),
    ]
