# Generated by Django 3.2.4 on 2022-07-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal_component', '0002_auto_20220705_0547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LectuterComment',
            new_name='LecturerComment',
        ),
    ]
