# Generated by Django 3.2.4 on 2022-07-06 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal_component', '0004_auto_20220705_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpcassessment',
            name='which_lecturer',
        ),
        migrations.RemoveField(
            model_name='hodassessment',
            name='comment_by_member_of_staff',
        ),
        migrations.AlterField(
            model_name='lecturercomment',
            name='get_appraisal',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lecturer_comment', to='appraisal_component.staffappraisal'),
        ),
    ]
