# Generated by Django 3.2.4 on 2022-07-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal_component', '0006_auto_20220706_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpcassessment',
            name='percentage',
            field=models.CharField(blank=True, default=0.0, max_length=100),
        ),
    ]
